const CHANGE_COUNTRY = "CHANGE_COUNTRY";
const REQUEST_DATA = "REQUEST_DATA";
const RECEIVED_DATA = "RECEIVED_DATA";
const FAILED_REQUEST = "FAILED_DATA";

export { CHANGE_COUNTRY, REQUEST_DATA, RECEIVED_DATA, FAILED_REQUEST };
